- src/contexts/events.tsx
- src/hooks/nabla/useTokenAmountOut.ts
- src/pages/swap/index.tsx
In GTM, I set up a new event 'GA4 Event | form_error' that groups all possible errors caused by the user input in the swap page form. I didn't want to add different events for each error, but instead added an 'error_message' parameter to them. To ensure that each `FormErrorEvent` only fires once, extra logic is added to the `trackEvent` function. 
While #143 does not define returning an error when exceeding the maximum withdrawal amount, I added it anyways because it seems related. 
Closes #143.
> Add unique identifiers for error messages to enable GTM tracking

- src/constants/constants.ts
- src/hooks/useMainProcess.ts
Adds a call to switch to polygon to the submission handler. If the user is already on Polygon, nothing happens and the flow continues as usual. The documentation for `isSwitchchain()` [here](https://wagmi.sh/react/api/hooks/useSwitchChain).
Closes #218.
> Add call to switch chain to submission handler

- src/pages/swap/index.tsx
#217 
The issue is that after our latest changes, `firstSep24ResponseState` is cleared quickly. When no `id` is passed, clicking `submit` on the email form does nothing. Also, we can see from failure screenshots that the `id` is not there anymore.
> Cache id to show in success and failure screen

- signer-service/src/api/services/pendulum.service.js
- signer-service/yarn.lock
Closes #248 
This solution avoids the memory leak and even after running for many requests, the heap will regularly be completely garbage collected.
However, I don't know whether this solution works reliably over a long time. I just tested locally and disconnected WIFI repeatedly and the service could successfully reconnect again. Unfortunately, I can't find any documentation for these functions.
> Only create api promise once

- src/contexts/events.tsx
- src/hooks/useMainProcess.ts
- src/pages/progress/index.tsx
I modified the GTM setup as follows:
- Rename `GA Event | transaction_failure` to `GA4 Event | transaction_failure`
- Add two new event parameters to `GA4 Event | transaction_failure`: `phase_name` and `phase_index`
- Add two new Variables `DLV | phase_index` and `DLV | phase_name`
- Modified the event parameters of `GA4 Event | progress` to use the new variables as well
- Deleted the variable `DLV | phase` and `DLV | progress name` (the naming was confusing and it's better to streamline with the other two news variables)
Closes #242.
> Add more information to GTM events

- src/components/AssetNumericInput/index.tsx
> implement styles for readonly input

- src/components/SigningBox/index.tsx
- src/components/Spinner.tsx
- src/components/buttons/SwapSubmitButton/index.tsx
Closes #260 
As I wrote on the ticket, this is a well-known bug in daisy-ui spinners: https://github.com/saadeghi/daisyui/issues/2570
I just replaced it with a very simple custom spinner using tailwind animation. I tested it on iOS Safari and it works reliably.
> Replace DaisyUI spinner with custom component

- src/contexts/events.tsx
It took me some time to figure out how to be able to properly watch the connected network. I noticed that the [watchChainId](https://wagmi.sh/core/api/actions/watchChainId) and [useChainId](https://wagmi.sh/react/api/hooks/useChainId) both don't fire when switching from or to a non-supported network, ie a network that is not defined in our `wagmiConfig`. Since only `polygon` is defined in our `wagmiConfig`, it never triggered when switching from any network to polygon.
Instead, we are now using the `chainId` contained in the data of the [useAccount](https://wagmi.sh/react/api/hooks/useAccount) hook as it's always updated when the network changes. 
- `DLV | from_network` and `DLV | to_network`
- `DLV | account_address`
- `DL Event | network_change`
- New event `GA4 Event | network_change` …
> 140 integrate additional events into google analytics query into the prototype

- src/components/AssetNumericInput/index.tsx
- src/components/NumericInput/index.tsx
- src/pages/swap/index.tsx
As described [here](https://github.com/pendulum-chain/vortex/issues/46#issuecomment-2273198079):
> event amount_type: sent when user edits the "from amount" field for the first time
This PR adds changes so that the event `amount_type` is emitted when the user changes the value of the `fromAmount` field. Since `amount_type` is included in the `UNIQUE_EVENT_TYPES`, the event will only get tracked once, even if `trackEvent()` fires multiple times. 
--- 
Closes #288.
> Track amount type event 

- signer-service/src/api/controllers/siwe.controller.js
Another unforeseen fix required after #257 
Cookies were set to `SameSite=Strict`, the issue is that our backend and frontend don't share the same home domain, and the cookie cannot be set on the deployment.
Regarding security:
This would open the possibility to CSRF attacks BUT we are also using CORS and limiting requests to the backend only from our deployments, so there should be no risk of that.
> Set to SameSite to None for auth cookie

- signer-service/src/constants/tokenConfig.js
This is a hotfix to use the new home domain of Mykobo.
See Slack for more info.
> Hotfix: Update the Mykobo home domain

- src/components/FeeComparison/index.tsx
- src/components/FeeComparison/quoteProviders.tsx
- src/components/Nabla/useSwapForm.tsx
- src/contexts/events.tsx
- src/hooks/useMainProcess.ts
- src/pages/failure/index.tsx
- src/pages/swap/index.tsx
- src/services/nabla.ts
- src/services/offrampingFlow.ts
- src/services/polkadot/index.tsx
- src/services/quotes/index.ts
- src/services/squidrouter/process.ts
- `GA4 Event | compare_quote`
- parameters:
-  `{{ Transaction Event Variables }}`
- `transak_quote`: `{{DLV | transak_quote}}`
- `moonpay_quote`: `{{DLV | moonpay_quote}}`
- `alchemypay_quote`: `{{DLV | alchemypay_quote}}`
- trigger
- `DL Event | compare_quote` 
- `GA4 Event | transaction_failure`
- changed parameters 
- `error_message`: `{{DLV | error_message}}` 
- Changes the emitted value of `to_amount` to the amount after fees
- Adds a new field `message` to `FailureType` so that the error message is available on the failure page (and is available  to emit in the respective event)
- The return values of `useSwapForm` were memoized to prevent infinite rerenders of the new `useEffect` hook in the `FeeProviderRow` component
- A new function `scheduleQuote()` was added to the events …
> Add new events to google analytics

- src/components/FeeComparison/index.tsx
- src/pages/swap/index.tsx
No issue created.
- Scroll to the beginning of the fee comparison table upon click of the button and using the deep link.
- Add an id to the overarching`FeeComparison` div.
- Use a state hook to detect when the `FeeComparison` element is visible, and only then scroll to it.
> Scroll to beginning of the comparison table.

- index.html
Prevent browser from suggesting translation on Vortex. Solution based on StackOverflow answer [here](https://stackoverflow.com/a/61363117). 
I tested this and with the new configuration, the browser will not even translate it if the user manually opens the translation box. Which I think is good. 
Closes #354.
> Add `notranslate` meta tag to prevent browser translation

- src/components/FeeComparison/index.tsx
- src/pages/swap/index.tsx
- Only scroll to the quote table when user clicks on 'Compare fees' button.
- Change the behavior of the 'Compare fees' button to always show the table and never hide it again. This means that the quote table will only be hidden when the user opens the page without `showCompareFees=true` (or with `showCompareFees=false`) and before clicking the 'Compare fees' button. 
Closes #361 and closes #372.
> Make deep link for quote comparison not scroll down but only open table

- index.html
Reverts pendulum-chain/vortex#359.
We saw that removing the option to translate the page makes users drop.
> Revert "Add `notranslate` meta tag to prevent browser translation"

- src/pages/swap/index.tsx
Updated initalization error message
> update initialization error message

- src/config/index.ts
---
Issue was related with incorrect `projectId` - we were using `projectId` from the **Portal**.
Close: #356
> [READY] Fix WalletConnect not loading

- src/wagmiConfig.ts
> Add custom RPCs for all evm chains

- src/constants/tokenConfig.ts
Mykobo raised their max withdrawal amount to 30k EUR. We set it to 10k EUR.
> Increase max withdrawal amount to 10000 EUR

- src/components/FeeComparison/index.tsx
- src/contexts/events.tsx
- src/pages/swap/index.tsx
Issue #411
We disable tracking of the quote event, until either the input field changes, or the user clicks on the `Compare Fees` button, even if this one is already expanded.
> Track quote only after user interaction

- src/components/NumericInput/index.tsx
- src/hooks/nabla/useTokenAmountOut.ts
- src/pages/swap/index.tsx
- src/pages/swap/useSwapUrlParams.ts
Issue: #421 
- Uses hard coded default values depending on the output amount, to have always a non-zero amount and show the compare fee section permanently.
- This also adds a new state to `useTokenAmountOut` hook, such that it returns loading when starting the app. Previously, this value was initially set to `false` which lead to "flickering" of the final quote.
>  Use default input amount to display fee section always.

- signer-service/src/config/express.js
Since https://github.com/pendulum-chain/tasks/issues/447 is done, we can re-add the `rateLimitNumberOfProxies` parameter and check for the correct number for the parameter.
> Readd `rateLimitNumberOfProxies` parameter

- src/components/TextInput/index.tsx
- src/pages/failure/index.tsx
Change the 'Reset and Restart' button to have a dashed border and change the styling of the email input field so that it's apparent to be an input field again. 
Before
After
> Change styling of reset and restart button

- signer-service/src/api/controllers/brla.controller.ts
- signer-service/src/api/services/brla/brlaApiService.ts
- signer-service/src/api/services/brla/webhooks.ts
- signer-service/src/index.ts
- src/components/Nabla/useSwapForm.tsx
- src/constants/tokenConfig.ts
- src/pages/swap/index.tsx
Replace polling of webhooks from the cache service, and fetch directly the events from BRLA API. 
Now, each time a user tries to fetch a status, we first query the last events from BRLA and return the last one, if relevant to the user's query.
Small fix for bug that prevents output token selection.
> Fetch events from BRLA API instead of webhooks cache.

- _redirects
Since the current production endpoint is not up-to-date we temporarily point to the staging endpoint.
> Make both production and staging point to the staging endpoint

- src/components/BrlaComponents/BrlaSwapFields/index.tsx
- src/components/Nabla/schema.tsx
- src/hooks/brla/useBRLAKYCProcess/index.tsx
Rename mentions of tax ID to CPF to make it clearer for Brazilian citizens. Also capitalize Pix to PIX.
> Rename text usages of tax ID to CPF

- src/hooks/useVortexAccount.ts
- src/pages/failure/index.tsx
- src/pages/swap/index.tsx
> Send custom error logs to sentry

- api/src/database/migrations/001-initial-schema.ts
This changes the order of the rampState table columns. It's easier to find data in a row if the large items come last. 
I adjusted the schema of the staging and production table already.
> Change column order of rampState table

- frontend/src/pages/success/index.tsx
- frontend/src/translations/en.json
- frontend/src/translations/pt.json
Show custom text on success page depending on on- or offramp.
> Adjust text for success page

- frontend/src/components/AccountCard/index.tsx
- frontend/src/components/RampSummaryDialog/FeeDetails.tsx
- frontend/src/components/RampSummaryDialog/TransactionTokensDisplay.tsx
- frontend/src/components/buttons/PolkadotWalletButton/PolkadotDisconnectWallet/index.tsx
- frontend/src/translations/en.json
- frontend/src/translations/pt.json
Adds changes to show the substrate account always in the format of the network. Since we only support Assethub at the moment, we are always using the ss58 format of Assethub.
Also adds the destination address to the onramp summary dialog.
> Show substrate account with ss58 format and show destination in onramp summary

- frontend/src/sections/PopularTokens/index.tsx
- frontend/src/translations/en.json
- frontend/src/translations/pt.json
- Adding buy along with sell to the static text [en]
> Add buy text

- api/src/api/services/moonbeam/balance.ts
- api/src/api/services/pendulum/apiManager.ts
- api/src/api/services/phases/handlers/brla-payout-moonbeam-handler.ts
- api/src/api/services/phases/handlers/brla-teleport-handler.ts
- Adds a callback to the `executeApiCall` of `ApiManager` such that it does not resolves unless the transaction has been including into the block. 
- Waits for BRLA tokens to arrive on the polygon network instead of moonbeam, for the phase `BrlaPayoutOnMoonbeamPhase`.
> Phase handlers improvements

- frontend/src/components/BrlaComponents/KYCForm/index.tsx
- frontend/src/components/Navbar/index.tsx
- frontend/src/components/RampSubmitButtons/index.tsx
- frontend/src/hooks/useWidgetMode.ts
- frontend/src/layouts/index.tsx
- frontend/src/pages/main/MainSections.tsx
- frontend/src/pages/main/index.tsx
When `mode=widget` is added to the url the widget mode is being activated.
> [READY] Add widget mode

- api/src/api/controllers/brla.controller.ts
- api/src/api/routes/v1/brla.route.ts
- api/src/api/services/brla/brlaApiService.ts
- api/src/api/services/brla/mappings.ts
- api/src/api/services/brla/types.ts
- api/src/api/services/phases/handlers/brla-teleport-handler.ts
- api/src/api/services/transactions/stellar/offrampTransaction.ts
- frontend/src/helpers/notifications.ts
- frontend/src/hooks/ramp/useRampSubmission.ts
- frontend/src/services/api/brla.service.ts
- frontend/src/services/initialChecks.ts
- frontend/src/translations/en.json
- frontend/src/translations/pt.json
- shared/src/endpoints/brla.endpoints.ts
- shared/src/helpers/signUnsigned.ts
Supersedes #533 and closes #518.
> Add check for BRL ramping amount

- api/src/api/services/phases/post-process/moonbeam-post-process-handler.ts
- api/src/api/services/transactions/onrampTransactions.ts
- Adjust the nonce value such that the correct one is used for Assethub type onramps.
- Delays moonbeam cleanup 15 minutes after complete to ensure squidrouter has time to refund.
> Adjust cleanup worker and nonces.

- frontend/src/sections/FeeComparison/index.tsx
Add logic to hide the fee comparison section for the ONRAMP direction. Ensures the section only displays when relevant, improving user experience and layout consistency.
> Refactor FeeComparison to conditionally render based on ramp direction

- api/src/api/controllers/brla.controller.ts
- api/src/api/controllers/googleSpreadSheet.controller.ts
- api/src/api/controllers/moonbeam.controller.ts
- api/src/api/controllers/pendulum.controller.ts
- api/src/api/controllers/price.controller.ts
- api/src/api/controllers/siwe.controller.ts
- api/src/api/controllers/stellar.controller.ts
- api/src/api/controllers/subsidize.controller.ts
- api/src/api/middlewares/auth.ts
- api/src/api/middlewares/validators.ts
- api/src/api/services/slack.service.ts
- api/webhooks-cache/index.js
- frontend/src/components/RampToggle/index.tsx
a new env variable `SLACK_USER_ID` ( Closes: #470 )
use `http-status` for api statuses ( Closes: #612 )
> [READY] use http-status for api responses

- frontend/src/pages/progress/index.tsx
- frontend/src/pages/progress/phaseMessages.ts
In order to avoid issues with percentage shown in the Progress page animation:
> fix multiple progress page animation intervals causing % above 100

- frontend/src/components/BrlaComponents/BrlaExtendedForm.tsx
- frontend/src/components/BrlaComponents/KYCForm/index.tsx
- frontend/src/components/BrlaComponents/KYCForm/useKYCFormLocalStorage.ts
- frontend/src/components/BrlaComponents/KYCLevel2Form/index.tsx
- frontend/src/components/BrlaComponents/useBrlaKycTaxIdLocalStorage.ts
- frontend/src/components/NetworkSelector/index.tsx
- frontend/src/components/RampToggle/index.tsx
- frontend/src/constants/localStorage.ts
- frontend/src/hooks/brla/useBRLAKYCProcess/index.tsx
- frontend/src/hooks/useConnectPolkadotWallet/index.tsx
- frontend/src/pages/ramp-form/index.tsx
- frontend/src/stores/ramp/useRampFormStore.ts
Show Nova Wallet connection option only when dApp is open in Nova app.
> [READY] filter out Nova Wallet option if not in the Nova app

- frontend/src/services/initialChecks.ts
This pull request includes cleanup and a logic correction in the `useRampAmountWithinAllowedLimits` function within `frontend/src/services/initialChecks.ts`. The changes improve code clarity and fix a conditional check.
Code cleanup:
* Removed unnecessary `console.log` statements that logged the `kycLevel` and `remainingLimitNum` values, reducing noise in the code. [[1]](diffhunk://#diff-815cf676864f7a643071acda6bddc6919ae8ab494676f0299bac2dadd84edad8L20) [[2]](diffhunk://#diff-815cf676864f7a643071acda6bddc6919ae8ab494676f0299bac2dadd84edad8L32-R32)
Logic correction:
* Updated the conditional check to correctly compare `amountNum` and `remainingLimitNum`, ensuring the function returns `true` when `amountNum` is less than or equal to `remainingLimitNum` instead of greater.
> Fix remaining limit check to allow valid amounts

- api/.eslintrc.js
- api/src/api/helpers/contracts.ts
- api/src/api/services/ramp/quote.service.ts
- api/src/api/services/transactions/onrampTransactions.ts
- frontend/src/hooks/useGetNetworkIcon.tsx
- frontend/src/pages/progress/index.tsx
- frontend/src/pages/progress/phaseMessages.ts
- frontend/src/translations/en.json
- frontend/src/translations/pt.json
- frontend/src/wagmiConfig.ts
- shared/src/helpers/networks.ts
- shared/src/tokens/evm/config.ts
> enable bnb chain 

- frontend/src/translations/en.json
- frontend/src/translations/pt.json
This pull request updates the promotional banner text in the English and Portuguese translation files to reflect a new end date for the special offer.
* Updated the `airdropBanner.title` in `frontend/src/translations/en.json` to change the offer end date from "20 May" to "27 May".
* Updated the `airdropBanner.title` in `frontend/src/translations/pt.json` to change the offer end date from "20 Maio" to "27 Maio".
> Change banner to extend campaign to 27 May

- frontend/src/hooks/offramp/useRampService/useStartRamp.ts
- frontend/src/hooks/offramp/useSubmitRamp.ts
- frontend/src/hooks/ramp/useQuoteService.ts
- frontend/src/hooks/ramp/useRampSubmission.ts
- frontend/src/hooks/useTrackRampConfirmation.ts
We called `transaction_confirmation` 3 times in incorrect places, now we call it only once after startRamp
> Transaction confirmation event fired incorrectly

- api/src/api/controllers/brla.controller.ts
- api/src/api/services/brla/helpers.ts
- api/src/api/workers/unhandled-payment.worker.ts
- api/src/index.ts
Adds a worker that fetches ramp entries with status `failed` and `initial`, using a predefined time window. 
For each ramp, the worker checks:
- If there was a payment with a reference label corresponding to the entry. This should not be the case and should be alerted.
- Checks if there is a duplicate reference label on the list of payments from the BRLA account corresponding to the entry. Rationale is that this may be the cause of a `failed` or `invalid` state.
- If there is a payment with an invalid label (no label, wrong length, etc).
The worker will not alert more than once per day for each`subaccountId`. If from a particular ramp state we detect multiple inconsistencies, then all will be triggered.
> Add unhandled payment alert worker

- api/.eslintrc.js
- api/src/api/controllers/cryptocurrencies.controller.ts
- api/src/api/controllers/payment-methods.controller.ts
- api/src/api/middlewares/validators.ts
- api/src/api/routes/v1/cryptocurrencies.route.ts
- api/src/api/routes/v1/index.ts
- api/src/api/routes/v1/payment-methods.route.ts
- api/src/api/services/transactions/squidrouter/offramp.ts
- api/src/config/cryptocurrencies.config.ts
- api/src/config/payment-methods.config.ts
- frontend/src/contexts/events.tsx
- shared/src/endpoints/index.ts
- shared/src/endpoints/payment-methods.endpoints.ts
- shared/src/endpoints/supported-cryptocurrencies.endpoints.ts
- shared/src/helpers/networks.ts
- shared/src/tokens/utils/helpers.ts
Add:
Example response:
```
{
paymentMethods: [
{ id: 'sepa', name: 'SEPA', supportedFiats: ['eurc'], limits: { min: 10, max: 50000 } },
{ id: 'pix', name: 'PIX', supportedFiats: ['brl'], limits: { min: 1, max: 500000 } },
{ id: 'cbu', name: 'CBU', supportedFiats: ['ars'], limits: { min: 1, max: 500000 } },
],
};
```
Example response:
```
{
cryptocurrencies: [
{
assetSymbol: 'USDC',
assetContractAddress: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
assetNetwork: 'polygon',
assetDecimals: 6,
},
{
assetSymbol: 'USDT',
assetContractAddress: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
assetNetwork: 'polygon',
assetDecimals: 6,
},
{
assetSymbol: 'USDC.e',
assetContractAddress: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
assetNetwork: 'polygon',
assetDecimals: 6,
},
],
};
```
For the …
> [READY] /supported-payment-methods & /supported-cryptocurrencies

- frontend/src/hooks/offramp/useSubmitRamp.ts
This pull request updates the `useSubmitRamp` hook to improve the calculation of `amountNum` by making it conditional on the ramp direction (`RampDirection.OFFRAMP` or `RampDirection.ONRAMP`).
Key change:
* [`frontend/src/hooks/offramp/useSubmitRamp.ts`](diffhunk://#diff-0018c5c5bdba4cc84de168b4ad2f3df159e417b2feadd34dd412bfc24c88b08bL86-R90): Modified the calculation of `amountNum` to use `executionInput.quote.outputAmount` for off-ramp transactions and `executionInput.quote.inputAmount` for on-ramp transactions, ensuring the correct value is used based on the ramp direction.
> Fix inputAmount used for remaining limit comparison for on and offramp

- .prettierrc
- apps/frontend/src/helpers/path/index.tsx
- apps/frontend/src/hooks/useRampUrlParams.ts
- apps/frontend/src/stores/ramp/useRampFormStore.ts
This pull request introduces several changes to improve code readability, standardize configurations, and enhance functionality in handling language-specific defaults. The most important changes include updates to the `.prettierrc` file for consistent formatting, adjustments to ramp direction logic based on language, and refactoring of default fiat token amounts for better maintainability.
* [`.prettierrc`](diffhunk://#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2R1-R8): Added a configuration file to enforce consistent code formatting, including rules for semicolons, trailing commas, single quotes, and print width.
* [`apps/frontend/src/helpers/path/index.tsx`](diffhunk://#diff-4ac51ced9b890244282de7f65870cbdbbf2e180451c45678712bcdba6114c08eL13-R19): Updated the …
> Update the default state of the app

- apps/api/src/api/controllers/payment-methods.controller.ts
- apps/api/src/config/payment-methods.config.ts
- packages/shared/src/endpoints/payment-methods.endpoints.ts
Refactored `supported-payment-methods` endpoint data format.
Before:
```
paymentMethods: [
{ id: 'sepa', name: 'SEPA', supportedFiats: ['eur'], limits: { min: 10, max: 50000 } },
{ id: 'pix', name: 'PIX', supportedFiats: ['brl'], limits: { min: 1, max: 500000 } },
{ id: 'cbu', name: 'CBU', supportedFiats: ['ars'], limits: { min: 1, max: 500000 } },
]
```
After:
```
paymentMethods: [
{ id: 'sepa', name: 'SEPA', supportedFiats: [{
id: 'eur',
name: 'EURO',
limits: { min: 10, max: 50000 }
}]
},
{ id: 'pix', name: 'PIX', supportedFiats: [{
id: 'brl',
name: 'Brazilian Real',
limits: { min: 1, max: 500000 }
}]
},
{ id: 'cbu', name: 'CBU', supportedFiats: [{
id: 'ars',
name: 'Argentine Peso',
limits: { min: 1, max: 500000 }
}]
},
]
```
> fix supported-payment-methods data format

- apps/api/src/api/services/priceFeed.service.ts
This pull request enhances the `PriceFeedService` in `apps/api/src/api/services/priceFeed.service.ts` by introducing a mechanism to monitor onchain oracle prices and notify via Slack if prices are outdated. It also includes improvements for periodic checks and logging.
* **Slack integration added**: Imported `SlackNotifier` to enable sending alerts to Slack when onchain oracle prices are outdated.
* **Onchain oracle price check implemented**: Added a new method `checkOnchainOraclePricesUpToDate` to verify if onchain oracle prices are updated within the last hour. Sends warnings to Slack for outdated prices and logs the status.
* **Cron job for daily checks**: Added a cron job in the `PriceFeedService` constructor to automatically check onchain oracle prices every 24 hours, ensuring …
> Implement Slack alert for outdated onchain oracle prices

- apps/frontend/src/hooks/ramp/useRampValidation.ts
- apps/frontend/src/stores/ramp/useQuoteStore.ts
- apps/frontend/src/translations/en.json
- apps/frontend/src/translations/pt.json
This pull request introduces changes to improve error handling and localization in the ramp validation and quote retrieval processes. Key updates include replacing hardcoded error messages with translatable keys, adding new translation entries, and refining input validation logic.
* Updated `useRampValidation` to return localized error messages by using the `t` function for translation (`apps/frontend/src/hooks/ramp/useRampValidation.ts`).
* Modified the `error` field in `QuoteState` to store either an error message or a translation key, enabling better localization (`apps/frontend/src/stores/ramp/useQuoteStore.ts`).
* Replaced hardcoded error messages with translation keys for invalid input amounts and failed quote retrieval in `useQuoteStore` …
> Fix quote validation and improve error handling for input amount

- packages/shared/src/services/squidrouter/route.ts
This pull request makes a minor adjustment to the slippage threshold in the `getRoute` function, increasing the limit for what is considered "high slippage" and slightly rewording the error message.
- Increased the threshold for high slippage from 1% to 2.5% in the `getRoute` function, and updated the error message for clarity (`packages/shared/src/services/squidrouter/route.ts`).
Closes #833.
> Increase slippage threshold for squidrouter

- apps/api/src/api/controllers/brla.controller.ts
- apps/api/src/api/services/phases/handlers/brla-onramp-mint-handler.ts
- apps/api/src/api/services/phases/handlers/brla-payout-moonbeam-handler.ts
- apps/api/src/api/services/phases/handlers/brla-teleport-handler.ts
- apps/api/src/api/services/phases/handlers/initial-phase-handler.ts
- apps/api/src/api/services/phases/handlers/monerium-onramp-mint-handler.ts
- apps/api/src/api/services/phases/meta-state-types.ts
- apps/api/src/api/services/phases/register-handlers.ts
- apps/api/src/api/services/ramp/ramp.service.ts
- apps/frontend/src/hooks/ramp/useRampSubmission.ts
- apps/frontend/src/machines/ramp.machine.ts
- apps/frontend/src/pages/progress/index.tsx
- apps/frontend/src/pages/progress/phaseMessages.ts
- apps/frontend/src/translations/en.json
- apps/frontend/src/translations/pt.json
- packages/shared/src/endpoints/ramp.endpoints.ts
- packages/shared/src/services/brla/brlaApiService.ts
- packages/shared/src/services/brla/mappings.ts
- packages/shared/src/services/brla/types.ts
This PR includes changes required to create onramp and offramp quotes and tickets. It also modifies accordingly backend   phase handlers.
- Modify Avenia's API service, quote and ticket query params.
- Modify `BrlaTeleportPhaseHandler`. The name of the phase is kept for the moment, yet no teleport seems to be required, we only wait for the mint on the destination chain.
- Adjust `BrlaPayoutOnMoonbeamPhaseHandler`.
> Enable Avenia onramps and offramps
