src/hooks/useMainProcess.ts
This is a follow up to [this PR](https://github.com/pendulum-chain/vortex/pull/168), which did only partially implement the requirements of the associated issue https://github.com/pendulum-chain/vortex/issues/156, see [this comment](https://github.com/pendulum-chain/vortex/issues/156#issuecomment-2377211856).
This PR here corrects that.
=> Fix the main button caption

src/components/Navbar/index.tsx
=> Add Alpha Tag to the logo

src/hooks/useMainProcess.ts, src/pages/swap/index.tsx, src/services/anchor/index.ts, src/services/offrampingFlow.ts
Related to #128.
We realize this will not fix the issue the user may see from waiting too much to click the second confirmation button.
This changes will refresh the sep24 url every 20 seconds until the user actually clicks on the button.
=> Check sep24 interactive URL

src/helpers/notifications.ts, src/hooks/useMainProcess.ts, src/pages/swap/index.tsx, src/services/anchor/index.ts
Related: [#tasks/396](https://github.com/pendulum-chain/tasks/issues/396)
Changes required to receive an event from the anchor site once the user completes the KYC flow successfully.
=> Closing Anchor KYC window on success.

src/hooks/useMainProcess.ts, src/pages/swap/index.tsx
Fix from commented out code that slipped from the last merged feature [PR](https://github.com/pendulum-chain/vortex/pull/187).
=> Fix for changes introduces in last PR.

src/components/SigningBox/index.tsx
=> Bug: UI signing box not properly in the foreground

src/config/index.ts, src/pages/failure/index.tsx
- Update the TG link to support link as all users are not expected to TG
=> updated tg link to support link

src/pages/progress/index.tsx
=> Add percentage view to success screen

signer-service/package.json, signer-service/yarn.lock
=> Bump dependency on signer-service

src/helpers/contracts.ts
=> Change gas limits for AMM calls

signer-service/package.json, signer-service/yarn.lock
Closes #250 
Turned out that upgrading to Express 5.0 resolved the problem.
=> Upgrade express version

src/components/Nabla/schema.tsx, src/components/Nabla/useSwapForm.tsx
=> Add url parameter to preselect tokens

src/pages/success/index.tsx, src/pages/swap/index.tsx
=> 264 text changes for ars offramp

src/contexts/events.tsx
=> Fix previousAddress sometimes undefined

signer-service/src/api/services/siwe.service.js, signer-service/src/constants/constants.js
=> Don't check domain for siwe message

src/components/buttons/AssetButton/index.tsx
=> Add downward arrow to asset dropdown

src/components/buttons/SwapSubmitButton/index.tsx, src/pages/swap/index.tsx
=> Make main buttons 50% width

src/components/Nabla/useSwapForm.tsx, src/pages/swap/index.tsx
=> Keep track of modal type and open states separately

src/components/Rating/index.tsx, src/components/buttons/EVMWalletButton/index.tsx, src/contexts/events.tsx, src/contexts/siwe.tsx, src/hooks/offramp/useSubmitOfframp.ts, src/hooks/useInputTokenBalance.ts, src/hooks/useSignChallenge.ts, src/hooks/useVortexAccount.ts, src/main.tsx, src/pages/progress/index.tsx, src/pages/swap/helpers/swapConfirm/index.ts, src/pages/swap/helpers/swapConfirm/performSwapInitialChecks.ts, src/pages/swap/index.tsx, src/services/anchor/index.ts, src/services/phases/squidrouter/route.ts, src/services/storage/remote.ts
=> Fix wrong use of evm account address for assethub offramp

src/components/FeeCollapse/index.tsx, src/pages/swap/index.tsx, src/pages/swap/useSwapUrlParams.ts
=> add fromAmount and showFees url params

src/pages/swap/index.tsx
=> fix size of swap to 384px

src/constants/tokenConfig.ts
Don't merge yet. 
Closes #387.
=> Change fee to 0.25%

src/config/index.ts, src/constants/tokenConfig.ts, src/pages/swap/index.tsx
This release adds the following changes:
- Adjust hardcoded fee for the EUR offramp
- Fix a bug with WalletConnect not working properly
=> Create production release

signer-service/src/config/express.js
Related to [Tasks/#446](https://github.com/pendulum-chain/tasks/issues/446)
=> More test changes for rate limiting issues.

src/constants/tokenConfig.ts
- Change the max error amount from 10000 to 5000
=> Updated the max error amount

src/pages/swap/index.tsx
=> Do not show errors if wallet is not connected.

src/assets/payments/bank.svg, src/components/PoweredBy/index.tsx, src/pages/swap/index.tsx
=> Change icons in form footer

.github/workflows/autodeploy.yaml
This will merge a config change from `staging` to `main`. The change itself is not intended to stay on `main` like this, but we merge it anyway, to prevent conflicts in that file in the future.
=> Merge staging to main

.github/workflows/autodeploy.yaml
Adjusts the autodeploy workflow file for `main`.
=> Change autodeploy workflow

src/hooks/useVortexAccount.ts, src/pages/swap/index.tsx
There was an unnecessary check for a polkadot wallet account. 
Closes #473.
=> Fix confirm button enabled without holding account balance

.github/workflows/autodeploy.yaml, src/components/WarningBanner/index.tsx
Changes the text of the warning banner shown on the progress screen to something less intimidating.
=> Change progress banner text

signer-service/src/api/controllers/stellar.controller.ts
Fixes a bug where the SEP-10 authentication failed because the memo was not accessed properly.
=> Fix wrong reference to memo

signer-service/src/api/controllers/brla.controller.ts, signer-service/src/api/services/brla/brlaApiService.ts, signer-service/src/api/services/brla/webhooks.ts, signer-service/src/index.ts, src/components/FeeComparison/index.tsx, src/components/Nabla/useSwapForm.tsx, src/constants/tokenConfig.ts, src/pages/swap/index.tsx
Note: Please, merge first #491 first.
Issue: #489.
This PR changes the formatting of the price provided by competitors, as well as a green highlight for the Vortex entry when the comparison is better.
=> 489 change formatstyling of quote comparison

src/components/BrlaComponents/KYCForm/index.tsx, src/components/BrlaComponents/VerificationStatus/index.tsx, src/components/Spinner.tsx, src/components/Spinner/index.tsx
I saw the Spinner styles have changed in some places in the app. The component now is unified and can receive the `theme` and `size` props.
=> refactor Spinner component

src/services/phases/polkadot/eventParsers.tsx, src/services/phases/polkadot/xcm/index.ts, src/services/phases/polkadot/xcm/moonbeam.ts, src/services/phases/signedTransactions.ts
- Fix destination interior order, causing an invalid xcm reception on the Moonbeam side
- Fixes event listening when sending XCM from pendulum.
- Nonce issues.
=> Fixes for Pendulum to Moonbeam XCM phase.

_redirects
Reverts pendulum-chain/vortex#510.
The deployment issues are fixed so we can revert these changes.
=> Revert "Make both production and staging point to the staging endpoint"

signer-service/src/constants/constants.ts
Rollbacks latest commit `91694591b439e836b66d0db5a4879da277948859`.
=> Specify proper glmr funding and minimum amounts.

src/pages/swap/useSwapUrlParams.ts, src/translations/en.json
- Text updated on the BRL success page
=> Text update

src/pages/swap/useSwapUrlParams.ts
=> Update default amount

src/pages/swap/useSwapUrlParams.ts
- Default amounts updated to 5 for BRL and 20 for ARS
=> Update BRL and ARS default

frontend/src/components/BenefitsList/index.tsx, frontend/src/components/FiatIcon/index.tsx, frontend/src/components/OfframpSummaryDialog/index.tsx, frontend/src/components/Ramp/Offramp/index.tsx, frontend/src/components/Ramp/Onramp/index.tsx, frontend/src/components/RampSubmitButtons/index.tsx, frontend/src/hooks/offramp/useRampService/useRegisterRamp.ts, frontend/src/hooks/ramp/useQuoteService.ts, frontend/src/hooks/ramp/useRampForm.ts, frontend/src/hooks/ramp/useRampValidation.ts, frontend/src/sections/FeeComparison/FeeComparisonTable/index.tsx, frontend/src/sections/FeeComparison/FeeProviderRow/index.tsx, frontend/src/stores/ramp/useQuoteStore.ts, frontend/src/stores/ramp/useRampFormStore.ts, frontend/src/translations/en.json, frontend/src/translations/pt.json
=> [READY] Fix Frontend Refactor Issues

frontend/src/components/Ramp/Offramp/index.tsx, frontend/src/components/Ramp/Onramp/index.tsx, frontend/src/components/RampSubmitButtons/index.tsx, frontend/src/hooks/offramp/useRampService/useRegisterRamp.ts, frontend/src/hooks/ramp/schema.ts, frontend/src/hooks/ramp/useRampValidation.ts, frontend/src/hooks/useRampUrlParams.ts, frontend/src/pages/ramp-form/index.tsx, frontend/src/stores/ramp/useRampFormStore.ts, shared/src/helpers/brla.ts, shared/src/helpers/signUnsigned.ts
Fixes an issue where a user cannot switch between modes and the default input amount is not set.
=> Fix url params

frontend/src/components/AirdropBanner/index.tsx, frontend/src/pages/ramp-form/index.tsx, frontend/src/translations/en.json, frontend/src/translations/pt.json
=> [READY] add airdrop banner

frontend/src/translations/en.json, frontend/src/translations/pt.json
=> change airdrop text

frontend/src/components/AirdropBanner/index.tsx, frontend/src/translations/en.json, frontend/src/translations/pt.json
This pull request updates the `AirdropBanner` component and its associated translations to include new information about reward distribution and improve clarity.
=> Change text in campaign banner

apps/frontend/src/hooks/ramp/useQuoteService.ts, apps/frontend/src/hooks/ramp/useRampForm.ts, apps/frontend/src/stores/ramp/useRampFormStore.ts
This pull request introduces enhancements to the ramp form and quote service functionality, focusing on enforcing constraints and improving state management. Key changes include adding a mechanism to validate constraints before fetching quotes, updating the ramp form store to track constraint direction, and ensuring these constraints are applied consistently.
* Updated `useQuoteService` to include a new dependency, `constraintsValid`, which ensures that constraints are valid before fetching quotes. This prevents unnecessary API calls when constraints are not met. (`apps/frontend/src/hooks/ramp/useQuoteService.ts`, [[1]](diffhunk://#diff-282f39d232b25896d9fd75771220ccbd28c6e07c0dad0a93b164def4dabe3c24R10) [[2]](diffhunk://#diff-282f39d232b25896d9fd75771220ccbd28c6e07c0dad0a93b164def4dabe3c2 …
=> check if token constraints are applied in the quoteService

apps/api/src/api/controllers/maintenance.controller.ts, apps/api/src/api/routes/v1/index.ts, apps/api/src/api/routes/v1/maintenance.route.ts, apps/api/src/api/services/maintenance.service.ts, apps/api/src/database/migrations/007-maintenance-schedules-table.ts, apps/api/src/database/seeders/maintenance-schedules.ts, apps/api/src/models/index.ts, apps/api/src/models/maintenanceSchedule.model.ts, apps/frontend/src/components/BrlaComponents/KYCForm/index.tsx, apps/frontend/src/components/BrlaComponents/KYCLevel2Form/index.tsx, apps/frontend/src/components/MaintenanceBanner/index.tsx, apps/frontend/src/components/buttons/SwapSubmitButton/index.tsx, apps/frontend/src/hooks/useMaintenanceAware.ts, apps/frontend/src/layouts/index.tsx, apps/frontend/src/services/api/index.ts, apps/frontend/src/services/api/maintenance.service.ts, apps/frontend/src/stores/maintenanceStore.ts, apps/frontend/src/translations/en.json, apps/frontend/src/translations/pt.json, docs/architecture/maintenance-feature-design.md, docs/features/maintenance-mode.md, memory-bank/activeContext.md, memory-bank/decisionLog.md
This pull request introduces a new feature for managing maintenance schedules and status across the backend and frontend. It includes the addition of database models, API endpoints, and frontend integration for maintenance-aware functionality. Below are the key changes grouped by theme. The changes deviate from the proposed changes in #315. This is because at the time, we didn't have a backend available. By now, we can build an even better solution. 
Closes #315. 
* Added `MaintenanceSchedule` model to represent maintenance schedules in the database, including attributes like `title`, `startDatetime`, `endDatetime`, and `isActiveConfig`. Includes indexes for efficient querying. (`apps/api/src/models/maintenanceSchedule.model.ts`, …
=> Add under maintenance page to vortex

apps/api/src/api/services/phases/handlers/pendulum-moonbeam-phase-handler.ts
Fixes a bug where BRL offramps get stuck in the 'pendulumToMoonbeam' phase.
=> Refactor pre-check conditions for ephemeral addresses in phase handler

apps/api/src/api/services/alchemypay/response-handler.ts, apps/frontend/src/sections/FeeComparison/FeeComparisonTable/hooks/useFeeComparisonData.ts
Currently, the data returned from Alchemypay is handled incorrectly, resulting in incorrect information being displayed on the frontend. This PR updates the way Alchemypay data is processed for the onramp
=> [READY] Fix Alchemypay comparison data

apps/frontend/src/hooks/useRampUrlParams.ts, apps/frontend/src/services/monerium/moneriumAuth.ts
=> Fix error fetching quote after cancelling a Monerium onramp.

apps/api/src/api/services/ramp/quote.service/index.ts
=> Fix: setting lower fee when using an invalid partnerId.

apps/rebalancer/src/services/indexer/index.ts, apps/rebalancer/src/utils/config.ts, packages/shared/src/services/evm/createServices.ts
There is a small issue about the key derivation that prevents the rebalancer from executing.
=> Fix rebalancer execution

apps/api/src/api/controllers/brla.controller.ts, apps/api/src/api/routes/v1/brla.route.ts, apps/api/src/api/services/ramp/ramp.service.ts, apps/api/src/database/migrations/011-allowed-tax-ids-table.ts, apps/api/src/models/index.ts, apps/api/src/models/taxId.model.ts, apps/frontend/src/hooks/offramp/useSubmitRamp.ts
=> Disable Brla account creation
